### ISSUE TITLE
Incorrectly mapped device.geo.lat and lon

### ISSUE THREAD

**Issue by myDisconnect** [google/openrtb-doubleclick#111]
Hi,

Similarly to https://github.com/google/openrtb-doubleclick/issues/110 both (_device.geo.lat_ and _device.geo.lon_) should be mapped to **double** instead of **string**
More: 
https://developers.google.com/ad-exchange/rtb/openrtb-guide or any openRTB spec

**Comment by opinali** [comment]
What do you mean? This one looks correct, the code uses the methods for doubles and I can see in the test outputs `"geo":{"lat":90.0,"lon":45.0,...}`. I've also checked the JSON produced by captured AdX requests and the lat/lon are being emitted as unquoted doubles.

**Comment by myDisconnect** [comment]
Thank you for fixing the issue.
