### ISSUE TITLE
Upgrading to support openrtb-adx.proto v28

### ISSUE THREAD

**Issue by gannonk08** [google/openrtb-doubleclick#125]
Is there a timeline for when this repo will incorporate openrtb-adx.proto v28 and thusly the GDPR consent fields?

https://developers.google.com/ad-exchange/rtb/downloads/openrtb-adx-proto

**Comment by opinali** [comment]
Yes, expecting to make that update tomorrow. :)

**Comment by gannonk08** [comment]
Awesome glad to hear

**Comment by opinali** [comment]
Released a few days ago, closing this.
