### ISSUE TITLE
[com.google.doubleclick.imp] how to change to "ext" in BidRequest

### ISSUE THREAD

**Issue by Unnamalai57** [google/openrtb-doubleclick#136]
This is my code used to generate bidRequest 
.setExtension(AdxExt.imp, AdxExt.ImpExt.newBuilder().setDfpAdUnitCode(adBlockInfo.getAdunitId().toString()).build()))

when I executed I get ImpExt object as
[com.google.doubleclick.imp] {
    dfp_ad_unit_code: "1ad35672-f820-47c8-91dc-bf8b08410cbd"
  }

How can I change "[com.google.doubleclick.imp]" to "ext"

can anyone help to solve this issue?

**Comment by opinali** [comment]
Hi, what you are trying to do here is not well supported by the Protobuf library.  The textual format of protos is meant for purposes like logging / debugging / testing, it's not meant to be used as a general purpose text representation e.g. for remoting or persistence.
