### ISSUE TITLE
Adomain <-> click_through_url

### ISSUE THREAD

**Issue by jihonrado** [google/openrtb-doubleclick#37]
Hi,

First of all, I want to thank you for this amazing library and documentation.

I ran into the very same problem [described here](https://github.com/google/openrtb-doubleclick/issues/13) and found that issue to know how to solve it.

Now, my understanding is that DoubleClick's "click_through_url" field  has the same purpose that the OpenRTB's "adomain" field. So, if I am not wrong, it would be nice to modify DoubleClick's mapper to map these two fields. What to you think?

Best,

**Comment by opinali** [comment]
I wish I could use that; unfortunately the spec is clear that `adomain` has to contain domain names, not full URLs. But AdX is more strict, it requires the full URLs for filtering and publisher blocks. I was tempted to put that in the `adomain` anyway, but that would be abusing the spec.

I have already suggested to change this in the spec, and there's other feedback showing that some people actually put full URLs in `adomain`, with the effect that others have to [**"clean them up to try and put them into true 'adomain' format"**](https://groups.google.com/forum/#!searchin/openrtb-dev/adomain/openrtb-dev/5sKOGJEa-lY/bJS4LhlvyI4J).

It was a hard choice, but we try to err in the side of spec compliance. I realize how inconvenient this is for fields that are as important as `click_through_url` (AdX will reject your bid if you don't send that), as opposed to so many other "nice-to-have" fields. We're considering some alternative solution, e.g. a configuration flag to ask the library to take some liberties with the spec where that would help to make a more complete mapping without extensions.

Meanwhile, the `DcExt` extensions should be a good workaround; they are in-memory extensions only (no JSON support) but that shouldn't be a problem for the native->OpenRTB usage scenario. You can also go to the openrtb-users list and add your vote to fix `adomain` ;-)

**Comment by jihonrado** [comment]
Thanks @opinali for the clarification. I imagined there was a reason for that. I will try the approach described in #13 then.

Best,

**Comment by opinali** [comment]
Some news here: I forgot to update this bug, but in the end we decided to go you way. Since 0.9.3, this library already supports mapping of `adomain`->`click_through_url`, but we support both domain names and URLs: you can put a domain name like "bidder.com" and it gets mapped to an URL like "http://domain/com" like AdX wants; or you can provide a full URL instead, which is mapped without change. The latter of course is non OpenRTB-compliant for now, but I hope we can get this improved in the spec.

**Comment by jihonrado** [comment]
Thanks for the update @opinali. We upgraded the library a few weeks ago and removed our custom implementation as now this is supported.
