### ISSUE TITLE
[Questions] Migrating from 0.8.2 to 1.0.0

### ISSUE THREAD

**Issue by Crystark** [google/openrtb-doubleclick#74]
Hi,

It's been a while since I've updated the version of `openrtb-doubleclick` we use but as we're facing some issues with the App/Site distinction I'm trying to do so now.
It seems like the code I had isn't directly compatible with 1.0.0 so had a few questions:

1- `DoubleClickOpenRtbMapper` used to be instantiated with a `DoubleClickCrypto.Hyperlocal` as parameter. I see it's not anymore. Is it now not useful anymore or am I missing something ?

2- I used to register on the `OpenRtbJsonFactory` a `OpenRtbJsonExtReader` named `BidExtReader` that would add the `click_through_url` field using the `NetworkBid.BidResponse.Ad.Builder.addClickThroughUrl` method (see https://github.com/google/openrtb-doubleclick/issues/13). It looks like this is no longer required and that the `click_through_url` is now mapped from the `adomain` field. Can you confirm that ?

Thanks
Regards

**Comment by opinali** [comment]
Hi Laurent,

1) Yes, the reason for not needing that is that AdX now requires bidders to use HTTPS so per-field encryption is redundant; the `encrypted_*` fields now have un-encrypted substitutes such as `hyperlocal_set`. There are some restricted cases where we will still allow HTTPS, but this doesn't justify anymore complicating the mapper with support for auto-decryption of internal fields. (In the rare case that you need that, you can still do this decryption manually with the `DoubleClickCrypto` utility; and as before, you still need that for the winning price.)

2) This is correct. Note that we make a small extension here: the `adomain` field, according to the spec, needs to be a domain name; but we support passing a full URL there.  (In terms of the mapping to the AdX `BidResponse`, the extension is the opposite: an URL is copied without change, a domain name will be canonicalized into an URL which is required by the AdX protocol.)

**Comment by Crystark** [comment]
Thanks for your answers :)
