### ISSUE TITLE
Add mapping from DoubleClick App category IDs to RTB App category

### ISSUE THREAD

**Issue by ashafey** [google/openrtb-doubleclick#86]
Looks like the mapping logic is there - it's just not being used to fill out the App.cat field

**Comment by opinali** [comment]
Yes, this mapping is still missing. To do this we need a metadata table mapping the Google Play & Apple AppStore app categories into IAB categories, which is still pending work.

**Comment by opinali** [comment]
This issue is way obsolete now, the mapper is totally gone from this library so this is now a problem for the native OpenRTB protocol. If this is still a problem please check with your DoubleClick account manager.
